# Можно задать необходимые правила по которым будут извлекаться строки из исходников.
# На данный момент доступно только правило ru_only - извлекать только строки на русском языке
rules:
  - "ru_only"

# Раздел с исключениями
excludes:
  # Заданные (файлы в след. версии) и папки будут проигнорированы при разборе
  path:
    - ".git"
    - "util"
    - "/Users/Dev/workspace/nova_health_mobile/lib/src/providers"

  # Указанные в данном массиве строки будут проигнорированы.
  # Также родительские строки составляющие данную строку будут проигнорированы при разборе
  prefix_excludes:
    - "import"
    - "initLogger"
    - "-e"
    - "e"
    - "-s"
    - "s"
    - "."
    - ","
    - "\\"
    - "/"
    - ".dart"
    - "dart"
    - " "
    - "GetStringsParse"
    - "excludes"
    - "path"
    - "[ЁёА-я].*"
    - '^([ёa-zA-ZА-Яа-я "-])+$'
    - '^([ёa-zA-ZА-Яа-я "-])+$'
